- name: Configure frontend Server
  hosts: frontend
  become: yes
  tasks:
  - name: Install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: installed
      
  - name: Enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent # this deletes the whole path/file

  - name: Create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory  

  - name: Download frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip    
      dest: /usr/share/nginx/html # we are sending to this location
      remote_src: yes   # this will give you access the remote location

  - name: copy expense config
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted